name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      # Ignore paths
      - '!tests/**'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Release Summary
        if: steps.semantic.outputs.new_release_published == 'true'
        shell: bash
        run: |
          echo '### Published release ${{ steps.semantic.outputs.new_release_version }} :rocket:' >> $GITHUB_STEP_SUMMARY
          echo 'Release Notes:'  >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.semantic.outputs.new_release_notes }}' >> $GITHUB_STEP_SUMMARY
